// Code generated by protoc-gen-go.
// source: protorpc.proto
// DO NOT EDIT!

/*
Package protorpcpb is a generated protocol buffer package.

It is generated from these files:
	protorpc.proto

It has these top-level messages:
	Request
	Response
*/
package protorpcpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Request struct {
	Method           *string `protobuf:"bytes,1,req,name=method" json:"method,omitempty"`
	Seq              *uint64 `protobuf:"varint,2,req,name=seq" json:"seq,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *Request) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

type Response struct {
	Method           *string `protobuf:"bytes,1,req,name=method" json:"method,omitempty"`
	Seq              *uint64 `protobuf:"varint,2,req,name=seq" json:"seq,omitempty"`
	Err              *string `protobuf:"bytes,3,req,name=err" json:"err,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *Response) GetSeq() uint64 {
	if m != nil && m.Seq != nil {
		return *m.Seq
	}
	return 0
}

func (m *Response) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "protorpcpb.Request")
	proto.RegisterType((*Response)(nil), "protorpcpb.Response")
}

var fileDescriptor0 = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0x2a, 0x48, 0xd6, 0x03, 0x33, 0x84, 0xb8, 0x60, 0xfc, 0x82, 0x24, 0x25, 0x35, 0x2e,
	0xf6, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x3e, 0x2e, 0xb6, 0xdc, 0xd4, 0x92, 0x8c,
	0xfc, 0x14, 0x09, 0x46, 0x05, 0x26, 0x0d, 0x4e, 0x21, 0x6e, 0x2e, 0xe6, 0xe2, 0xd4, 0x42, 0x09,
	0x26, 0x20, 0x87, 0x45, 0xc9, 0x84, 0x8b, 0x23, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x15,
	0xaf, 0x42, 0x10, 0x27, 0xb5, 0xa8, 0x48, 0x82, 0x19, 0x24, 0x03, 0x08, 0x00, 0x00, 0xff, 0xff,
	0xbb, 0x1e, 0xeb, 0x7d, 0x7a, 0x00, 0x00, 0x00,
}
