// Code generated by protoc-gen-go.
// source: testpb.proto
// DO NOT EDIT!

/*
Package testpb is a generated protocol buffer package.

It is generated from these files:
	testpb.proto

It has these top-level messages:
	Header
	GetAccessPointReq
	GetAccessPointRsp
*/
package testpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Header struct {
	Seq int64 `protobuf:"varint,1,opt,name=Seq" json:"Seq,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Header) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type GetAccessPointReq struct {
	Header     *Header `protobuf:"bytes,1,opt,name=Header" json:"Header,omitempty"`
	AccessType string  `protobuf:"bytes,2,opt,name=AccessType" json:"AccessType,omitempty"`
}

func (m *GetAccessPointReq) Reset()                    { *m = GetAccessPointReq{} }
func (m *GetAccessPointReq) String() string            { return proto.CompactTextString(m) }
func (*GetAccessPointReq) ProtoMessage()               {}
func (*GetAccessPointReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetAccessPointReq) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetAccessPointReq) GetAccessType() string {
	if m != nil {
		return m.AccessType
	}
	return ""
}

type GetAccessPointRsp struct {
	Header *Header  `protobuf:"bytes,1,opt,name=Header" json:"Header,omitempty"`
	Addrs  []string `protobuf:"bytes,2,rep,name=Addrs" json:"Addrs,omitempty"`
}

func (m *GetAccessPointRsp) Reset()                    { *m = GetAccessPointRsp{} }
func (m *GetAccessPointRsp) String() string            { return proto.CompactTextString(m) }
func (*GetAccessPointRsp) ProtoMessage()               {}
func (*GetAccessPointRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetAccessPointRsp) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetAccessPointRsp) GetAddrs() []string {
	if m != nil {
		return m.Addrs
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "testpb.Header")
	proto.RegisterType((*GetAccessPointReq)(nil), "testpb.GetAccessPointReq")
	proto.RegisterType((*GetAccessPointRsp)(nil), "testpb.GetAccessPointRsp")
}

func init() { proto.RegisterFile("testpb.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x49, 0x2d, 0x2e,
	0x29, 0x48, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xa4, 0xb8, 0xd8,
	0x3c, 0x52, 0x13, 0x53, 0x52, 0x8b, 0x84, 0x04, 0xb8, 0x98, 0x83, 0x53, 0x0b, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x98, 0x83, 0x40, 0x4c, 0xa5, 0x68, 0x2e, 0x41, 0xf7, 0xd4, 0x12, 0xc7, 0xe4, 0xe4,
	0xd4, 0xe2, 0xe2, 0x80, 0xfc, 0xcc, 0xbc, 0x92, 0xa0, 0xd4, 0x42, 0x21, 0x35, 0x98, 0x06, 0xb0,
	0x4a, 0x6e, 0x23, 0x3e, 0x3d, 0xa8, 0xb9, 0x10, 0xd1, 0x20, 0x98, 0x71, 0x72, 0x5c, 0x5c, 0x10,
	0x9d, 0x21, 0x95, 0x05, 0xa9, 0x12, 0x4c, 0x40, 0xb5, 0x9c, 0x41, 0x48, 0x22, 0x4a, 0x81, 0x18,
	0x86, 0x17, 0x17, 0x10, 0x6d, 0xb8, 0x08, 0x17, 0xab, 0x63, 0x4a, 0x4a, 0x51, 0x31, 0xd0, 0x5c,
	0x66, 0xa0, 0xb9, 0x10, 0x4e, 0x12, 0x1b, 0xd8, 0x6b, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x5f, 0x15, 0x42, 0x18, 0xea, 0x00, 0x00, 0x00,
}
